version: "3.4"

services:
#  crawler:
#    build:
#      context: ../
#      dockerfile: .
#    container_name: spacebox-crawler
#    environment:
#      ENV_FILE: ".env"
#    depends_on:
#      - zookeeper
#      - kafka
#      - mongo
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: spacebox-zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
  kafka:
    image: bitnami/kafka:3.3.1
    container_name: spacebox-kafka
#    networks:
#      - app-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: unless-stopped
    depends_on:
      - zookeeper
  mongo:
    image: mongo:6.0.3
    restart: always
    hostname: mongo
    container_name: spacebox-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: space_box_user
      MONGO_INITDB_ROOT_PASSWORD: space_box_password
      MONGO_INITDB_DATABASE: spacebox
    ports:
      - "27018:27017"
    volumes:
      - ./volumes/mongo:/data/db