name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        echo ${{github.ref}}
        echo ${{github.head_ref}}
        echo ${{github.base_ref}}
        docker build --tag hexydev/spacebox-crawler:${{github.ref}} --target=app .
    - name: push to registry
      run: |
        docker ps
        // docker push ${{secrets.DOCKERHUB_REPO}}
